wordpress:
    image: wordpress
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=passwd
     - WORDPRESS_DB_USER=root
    ports:
     - "localhost:80:80"
    volumes:
     - ./html:/var/www/html
mariadb:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=passwd
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql

# change !placeholder! to desired password
# change loclahost to your local ip
